### ISSUE TITLE
check file "exercise1.php"

### ISSUE THREAD

**Issue by tommykarjamenawi** [tommykarjamenawi/php-homework#1]
i made a full website where i can check what age the person is.
i also made some error checking in my code.
If i made any mistakes please let me know!

**Comment by wimmelstein** [comment]
Sorry, Tommy. I appreciate your enthusiasm, but your question goes way beyond of the scope of the lessons now. I don't have time for these kinds of questions. Please come back to me when we have arrived at the point that it makes sense to address this question.
